# openai-utils

[project]
name = "openai-utils"
version = "0.0.1"
requires-python = ">=3.8.10"
dependencies = [
    "rich",
    "openai",
    "tiktoken",
    "unidecode",
    "python-dotenv",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

